[package]
name = "xv6fs"
version = "0.1.0"
authors = ["foreverbell <dql.foreverbell@gmail.com>"]

[dependencies]
fuse = "0.3"
libc = "*"
time = "*"
lazy_static = "1.0"
bitflags = "1.0"
threadpool = "1.7"
